---
title: "review_lq_code"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{review_lq_code}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(wbpip)
```

## Background
Povcalnet uses two methods to estimate poverty and inequality statistics from 
grouped data.  
* One method is based on fitting a Lorenz Quadratic functional form to the 
grouped data  
* the other one uses a Beta Lorenz function

This vignette focuses on the Lorenz Quadratic method.

## High level example
```{r}
# Input definition
welfare_mean    <- 51.56
ppp             <- 3.69
daily_povline   <- 1.9
monthly_povline <- daily_povline * 365 / 12

# Create grouped data (Type 1)
# http://iresearch.worldbank.org/povcalnet/PovCalculator.aspx
population <- c(0.0005,
                0.0032,
                0.014799999999999999,
                0.0443,
                0.0991,
                0.257,
                0.4385,
                0.5938,
                0.7089,
                1)

welfare <- c(5.824760527229386e-05,
             0.000604029410841011,
             0.0037949334793616948,
             0.013988878652244477,
             0.036992164583098786,
             0.12140708906131342,
             0.24531391873082081,
             0.37446670169288321,
             0.48753116241194566,
             1)

df <- data.frame(population = population,
                 welfare    = welfare)


#--------- Data from DATT 1998 ---------
# Source:http://ebrary.ifpri.org/utils/getfile/collection/p15738coll2/id/125673/filename/125704.pdf
# Table 1
# Identify the type of data
# Type 1 grouped data: 
#  P=Cumulative proportion of population, 
#  L=Cumulative proportion of income held by that proportion of the population
# Type 5 grouped data: 
#  W=Percentage of the population in a given interval of incomes, 
#  X=The mean income of that interval.

datt <- tibble::tribble(
         ~W,    ~X,      ~P,      ~L,
        0.92,   24.84,  0.0092, 0.00208,
        2.47,    35.8,  0.0339, 0.01013,
        5.11,   45.36,   0.085, 0.03122,
         7.9,    55.1,   0.164, 0.07083,
        9.69,   64.92,  0.2609, 0.12808,
       15.24,   77.08,  0.4133, 0.23498,
       13.64,   91.75,  0.5497, 0.34887,
       16.99,  110.64,  0.7196, 0.51994,
          10,   134.9,  0.8196,  0.6427,
        9.78,  167.76,  0.9174, 0.79201,
        3.96,  215.48,   0.957, 0.86966,
        1.81,  261.66,  0.9751, 0.91277,
        2.49,  384.97,       1,       1
  )

datt$W <- datt$W/100

# Estimate poverty statistics
gd_compute_pip_stats_lq(.data           = df,
                        mean            = welfare_mean,
                        povline         = monthly_povline,
                        default_ppp     = ppp)
```
